// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomId: __t.u64().name("room_id"),
  x: __t.f64(),
  y: __t.f64(),
  angle: __t.f64(),
  score: __t.u32(),
  alive: __t.bool(),
  segmentsCount: __t.u32().name("segments_count"),
  boosting: __t.bool(),
  skinJson: __t.string().name("skin_json"),
  name: __t.string(),
});
