// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  slug: __t.string(),
  name: __t.string(),
  host: __t.identity(),
  isPublic: __t.bool().name("is_public"),
  gameMode: __t.string().name("game_mode"),
  maxPlayers: __t.u32().name("max_players"),
  seed: __t.u32(),
  createdAt: __t.timestamp().name("created_at"),
});
