// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCoinsReducer from "../add_coins_reducer";
import BroadcastGameEventReducer from "../broadcast_game_event_reducer";
import ClearGameEventsReducer from "../clear_game_events_reducer";
import CreateRoomReducer from "../create_room_reducer";
import DeleteRoomReducer from "../delete_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import MarkEliminatedReducer from "../mark_eliminated_reducer";
import ReportWinReducer from "../report_win_reducer";
import SetUsernameReducer from "../set_username_reducer";
import UpdateGameModeReducer from "../update_game_mode_reducer";
import UpdatePlayerStateReducer from "../update_player_state_reducer";

export type AddCoinsParams = __Infer<typeof AddCoinsReducer>;
export type BroadcastGameEventParams = __Infer<typeof BroadcastGameEventReducer>;
export type ClearGameEventsParams = __Infer<typeof ClearGameEventsReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DeleteRoomParams = __Infer<typeof DeleteRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type MarkEliminatedParams = __Infer<typeof MarkEliminatedReducer>;
export type ReportWinParams = __Infer<typeof ReportWinReducer>;
export type SetUsernameParams = __Infer<typeof SetUsernameReducer>;
export type UpdateGameModeParams = __Infer<typeof UpdateGameModeReducer>;
export type UpdatePlayerStateParams = __Infer<typeof UpdatePlayerStateReducer>;

