import type { ImageSourcePropType } from "react-native";

/**
 * Mapping of flag display names to their image sources.
 * Names match the FLAG_SKINS array in ShopScreen.tsx.
 */
export const FLAG_IMAGES: Record<string, ImageSourcePropType> = {
  // Europe
  France: require("../../drapeau/france.png"),
  Allemagne: require("../../drapeau/allemagne.png"),
  Italie: require("../../drapeau/italie.png"),
  Espagne: require("../../drapeau/espagne.png"),
  Portugal: require("../../drapeau/portugal.png"),
  "Royaume-Uni": require("../../drapeau/angleterre.png"),
  Belgique: require("../../drapeau/belgique.png"),
  "Pays-Bas": require("../../drapeau/pays-bas.png"),
  Suisse: require("../../drapeau/suisse.png"),
  Suede: require("../../drapeau/suede.png"),
  Pologne: require("../../drapeau/pologne.png"),
  Ukraine: require("../../drapeau/ukraine.png"),
  Grece: require("../../drapeau/grece.png"),
  Roumanie: require("../../drapeau/roumanie.png"),
  Irlande: require("../../drapeau/irlande.png"),
  Croatie: require("../../drapeau/croatie.png"),
  Norvege: require("../../drapeau/norvege.png"),
  Danemark: require("../../drapeau/danemark.png"),
  Finlande: require("../../drapeau/finlande.png"),
  Russie: require("../../drapeau/russie.png"),
  Turquie: require("../../drapeau/turquie.png"),
  Albanie: require("../../drapeau/albanie.png"),
  Andorre: require("../../drapeau/andorre.png"),
  Armenie: require("../../drapeau/armenie.png"),
  Azerbaidjan: require("../../drapeau/azerbaidjan.png"),
  Bielorussie: require("../../drapeau/bielorussie.png"),
  Bosnie: require("../../drapeau/bosnie.png"),
  Bulgarie: require("../../drapeau/bulgarie.png"),
  Chypre: require("../../drapeau/chypre.png"),
  Estonie: require("../../drapeau/estonie.png"),
  Georgie: require("../../drapeau/georgie.png"),
  Hongrie: require("../../drapeau/hongrie.png"),
  Islande: require("../../drapeau/islande.png"),
  Kosovo: require("../../drapeau/kosovo.png"),
  Lettonie: require("../../drapeau/lettonie.png"),
  Liechtenstein: require("../../drapeau/liechtenstein.png"),
  Lituanie: require("../../drapeau/lituanie.png"),
  Luxembourg: require("../../drapeau/luxembourg.png"),
  "Macedoine du Nord": require("../../drapeau/macedoine-du-nord.png"),
  Malte: require("../../drapeau/malte.png"),
  Moldavie: require("../../drapeau/moldavie.png"),
  Monaco: require("../../drapeau/monaco.png"),
  Montenegro: require("../../drapeau/montenegro.png"),
  "Saint-Marin": require("../../drapeau/saint-marin.png"),
  Serbie: require("../../drapeau/serbie.png"),
  Slovaquie: require("../../drapeau/slovaquie.png"),
  Slovenie: require("../../drapeau/slovenie.png"),
  Tchad: require("../../drapeau/tchad.png"),
  Tchequie: require("../../drapeau/tchequie.png"),
  Vatican: require("../../drapeau/vatican.png"),
  // Americas
  USA: require("../../drapeau/etat unis.png"),
  Canada: require("../../drapeau/canada.png"),
  Mexique: require("../../drapeau/mexique.png"),
  Bresil: require("../../drapeau/bresil.png"),
  Argentine: require("../../drapeau/argentine.png"),
  Colombie: require("../../drapeau/colombie.png"),
  Chili: require("../../drapeau/chili.png"),
  Perou: require("../../drapeau/perou.png"),
  Jamaique: require("../../drapeau/jamaique.png"),
  Bolivie: require("../../drapeau/bolivie.png"),
  "Costa Rica": require("../../drapeau/costa-rica.png"),
  Equateur: require("../../drapeau/equateur.png"),
  "El Salvador": require("../../drapeau/el-salvador.png"),
  Guatemala: require("../../drapeau/guatemala.png"),
  Guyana: require("../../drapeau/guyana.png"),
  Honduras: require("../../drapeau/honduras.png"),
  Nicaragua: require("../../drapeau/nicaragua.png"),
  Panama: require("../../drapeau/panama.png"),
  Paraguay: require("../../drapeau/paraguay.png"),
  Suriname: require("../../drapeau/suriname.png"),
  Uruguay: require("../../drapeau/uruguay.png"),
  Venezuela: require("../../drapeau/venezuela.png"),
  "Trinite-et-Tobago": require("../../drapeau/trinite-et-tobago.png"),
  Barbade: require("../../drapeau/barbade.png"),
  // Africa
  Maroc: require("../../drapeau/maroc.png"),
  Algerie: require("../../drapeau/algerie.png"),
  Tunisie: require("../../drapeau/tunisie.png"),
  Egypte: require("../../drapeau/egypte.png"),
  Senegal: require("../../drapeau/senegal.png"),
  Nigeria: require("../../drapeau/nigeria.png"),
  "Afrique du Sud": require("../../drapeau/afrique-du-sud.png"),
  Cameroun: require("../../drapeau/cameroun.png"),
  "Cote d'Ivoire": require("../../drapeau/cote-divoire.png"),
  Ghana: require("../../drapeau/ghana.png"),
  Congo: require("../../drapeau/congo.png"),
  Ethiopie: require("../../drapeau/ethiopie.png"),
  Angola: require("../../drapeau/angola.png"),
  Benin: require("../../drapeau/benin.png"),
  Botswana: require("../../drapeau/botswana.png"),
  "Burkina Faso": require("../../drapeau/burkina-faso.png"),
  Burundi: require("../../drapeau/burundi.png"),
  "Cap-Vert": require("../../drapeau/cap-vert.png"),
  Centrafrique: require("../../drapeau/centrafrique.png"),
  Djibouti: require("../../drapeau/djibouti.png"),
  Eswatini: require("../../drapeau/eswatini.png"),
  Erythree: require("../../drapeau/erythree.png"),
  Gabon: require("../../drapeau/gabon.png"),
  Gambie: require("../../drapeau/gambie.png"),
  Guinee: require("../../drapeau/guinee.png"),
  "Guinee-Bissau": require("../../drapeau/guinee-bissau.png"),
  "Guinee Equatoriale": require("../../drapeau/guinee-equatoriale.png"),
  Kenya: require("../../drapeau/kenya.png"),
  Lesotho: require("../../drapeau/lesotho.png"),
  Liberia: require("../../drapeau/liberia.png"),
  Libye: require("../../drapeau/libye.png"),
  Madagascar: require("../../drapeau/madagascar.png"),
  Malawi: require("../../drapeau/malawi.png"),
  Mali: require("../../drapeau/mali.png"),
  Mauritanie: require("../../drapeau/mauritanie.png"),
  Maurice: require("../../drapeau/maurice.png"),
  Mozambique: require("../../drapeau/mozambique.png"),
  Namibie: require("../../drapeau/namibie.png"),
  Niger: require("../../drapeau/niger.png"),
  Ouganda: require("../../drapeau/ouganda.png"),
  Rwanda: require("../../drapeau/rwanda.png"),
  Seychelles: require("../../drapeau/seychelles.png"),
  "Sierra Leone": require("../../drapeau/sierra-leone.png"),
  Somalie: require("../../drapeau/somalie.png"),
  Soudan: require("../../drapeau/soudan.png"),
  "Soudan du Sud": require("../../drapeau/soudan-du-sud.png"),
  Tanzanie: require("../../drapeau/tanzanie.png"),
  Togo: require("../../drapeau/togo.png"),
  Zimbabwe: require("../../drapeau/zimbabwe.png"),
  Zambie: require("../../drapeau/zambie.png"),
  // Asia
  Japon: require("../../drapeau/japon.png"),
  Chine: require("../../drapeau/chine.png"),
  "Coree du Sud": require("../../drapeau/coree-du-sud.png"),
  Inde: require("../../drapeau/inde.png"),
  Pakistan: require("../../drapeau/pakistan.png"),
  Indonesie: require("../../drapeau/indonesie.png"),
  Philippines: require("../../drapeau/philippines.png"),
  Vietnam: require("../../drapeau/vietnam.png"),
  Thailande: require("../../drapeau/thailande.png"),
  "Arabie Saoudite": require("../../drapeau/arabie-saoudite.png"),
  Iran: require("../../drapeau/iran.png"),
  Afghanistan: require("../../drapeau/afghanistan.png"),
  Bangladesh: require("../../drapeau/bangladesh.png"),
  Bhoutan: require("../../drapeau/bhoutan.png"),
  Brunei: require("../../drapeau/brunei.png"),
  Cambodge: require("../../drapeau/cambodge.png"),
  "Coree du Nord": require("../../drapeau/coree-du-nord.png"),
  Irak: require("../../drapeau/irak.png"),
  Jordanie: require("../../drapeau/jordanie.png"),
  Kazakhstan: require("../../drapeau/kazakhstan.png"),
  Kirghizistan: require("../../drapeau/kirghizistan.png"),
  Koweit: require("../../drapeau/koweit.png"),
  Laos: require("../../drapeau/laos.png"),
  Liban: require("../../drapeau/liban.png"),
  Maldives: require("../../drapeau/maldives.png"),
  Mongolie: require("../../drapeau/mongolie.png"),
  Myanmar: require("../../drapeau/myanmar.png"),
  Nepal: require("../../drapeau/nepal.png"),
  Oman: require("../../drapeau/oman.png"),
  Qatar: require("../../drapeau/qatar.png"),
  Singapour: require("../../drapeau/singapour.png"),
  "Sri Lanka": require("../../drapeau/sri-lanka.png"),
  Syrie: require("../../drapeau/syrie.png"),
  Tadjikistan: require("../../drapeau/tadjikistan.png"),
  Taiwan: require("../../drapeau/taiwan.png"),
  Turkmenistan: require("../../drapeau/turkmenistan.png"),
  Ouzbekistan: require("../../drapeau/ouzbekistan.png"),
  Malaisie: require("../../drapeau/malaisie.png"),
  Yemen: require("../../drapeau/yemen.png"),
  // Oceania
  Australie: require("../../drapeau/australie.png"),
  "Nouvelle-Zelande": require("../../drapeau/nouvelle-zelande.png"),
  Fidji: require("../../drapeau/fidji.png"),
  Palaos: require("../../drapeau/palaos.png"),
  "Papouasie-Nouvelle-Guinee": require("../../drapeau/papouasie-nouvelle-guinee.png"),
  Samoa: require("../../drapeau/samoa.png"),
  "Iles Salomon": require("../../drapeau/iles-salomon.png"),
  Tonga: require("../../drapeau/tonga.png"),
  Tuvalu: require("../../drapeau/tuvalu.png"),
  Vanuatu: require("../../drapeau/vanuatu.png"),
  "Timor Oriental": require("../../drapeau/timor-oriental.png"),
  // Caribbean / Islands
  Haiti: require("../../drapeau/haiti.png"),
  Cuba: require("../../drapeau/cuba.png"),
  "Rep. Dominicaine": require("../../drapeau/rep-dominicaine.png"),
  "Antigua-et-Barbuda": require("../../drapeau/antigua-et-barbuda.png"),
  Bahamas: require("../../drapeau/bahamas.png"),
  Bahrein: require("../../drapeau/bahrein.png"),
  Belize: require("../../drapeau/belize.png"),
  Dominique: require("../../drapeau/dominique.png"),
  "Sao Tome": require("../../drapeau/sao-tome.png"),
  // Middle East
  Israel: require("../../drapeau/israel.png"),
  Palestine: require("../../drapeau/palestine.png"),
  "Emirats Arabes Unis": require("../../drapeau/emirats-arabes-unis.png"),
};
